// Cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SAVE_CART = 'SAVE_CART';

// Productos
export const FETCH_PRODUCT = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_BY_CATEGORY = 'FETCH_PRODUCTS_BY_CATEGORY';
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT';
export const PRODUCT_AMOUNT = 'PRODUCT_AMOUNT'; // wtf 
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';