//SALE_REDUCER
export const CREATE_SALE = 'CREATE_SALE';
export const SEND_EMAIL_AFTER_CHECKOUT = 'SEND_EMAIL_AFTER_CHECKOUT';
export const SEND_EMAIL_STATUS = 'SEND_EMAIL_STATUS';

//USER_REDUCER
export const ADD_REVIEW = 'ADD_REVIEW';
export const FETCH_ORDERS_USER = 'FETCH_ORDERS_USER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SIGN_UP = 'SIGN_UP';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const FETCH_USERS = 'FETCH_USERS';
export const MAKE_ADMIN = 'MAKE_ADMIN';

// Carrito

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SAVE_CART = 'SAVE_CART';
export const ADD_Q_TO_PRODUCTO = 'ADD_Q_TO_PRODUCTO';
export const LESS_Q_TO_PRODUCTO = 'LESS_Q_TO_PRODUCTO';
export const UPDATE_CART = 'UPDATE_CART';

// Productos
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_USER = 'FETCH_PRODUCTS_USER';
export const FETCH_SINGLE_PRODUCT_wCATEGORIES = 'FETCH_SINGLE_PRODUCT_wCATEGORIES';
export const FETCH_PRODUCTS_BY_CATEGORY = 'FETCH_PRODUCTS_BY_CATEGORY';
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT';
export const PRODUCT_AMOUNT = 'PRODUCT_AMOUNT'; // wtf
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

// User admin
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
FETCH_CATEGORYS;
export const FETCH_CATEGORYS = 'FETCH_CATEGORYS';
export const FETCH_ORDERS_ADMIN = 'FETCH_ORDERS_ADMIN';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const UPDATE_ORDERS = 'UPDATE_ORDERS';
export const UPDATE_USER = 'UPDATE_USER';
